name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            # 🎉 Welcome to sticky-memo!
            
            Thank you for your first pull request! The Wisdom Fox community truly appreciates your contribution.
                    
            Need help? Don't hesitate to ask questions in the comments!
            Thank you for helping make sticky-memo better! 🚀
