name: Mark stale issues and PRs

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: '📢 This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions! If you are still working on this PR, please remove the stale label or add a comment.'
        close-pr-message: '🔒 This PR was closed because it has been stale for too long. Feel free to reopen it once you are ready to continue working on it.'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'pinned,security,work-in-progress'
        days-before-stale: 30
        days-before-close: 7
